name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: 
      - master
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: SiYuan-Lee/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: e3292d0d0b213f24e01fe10ee29a1e1b
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
